Skip oslo.log 4.8.0
oslo.log 4.8.0 added by default the logging of global_request_id which
when not passed as an argument it will fail with the following error
message:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 440, in format
    return self._format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 436, in _format
    return self._fmt % record.__dict__
KeyError: 'global_request_id'

Tempest logs each http request, so this issue makes the terminal
littered with stacktraces.

See LP: #1972974 for more details.